language: php
php:
- 7.0

notifications:
  email: false

before_install:
- mysql -e 'CREATE DATABASE o2n_test;'

before_script:
- cd api/lumen
- cp .env.travis .env
- composer install
- php artisan migrate:install
- php artisan migrate
- php artisan db:seed
- cd ../../client
- . $HOME/.nvm/nvm.sh
- nvm install node
- nvm use node
- npm install

script:
- cd ../api/lumen && ./vendor/bin/phpunit
- cd ../../client && npm run test

before_deploy:
- cd ..
- openssl aes-256-cbc -K $encrypted_70caed730726_key -iv $encrypted_70caed730726_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

deploy:
- provider: script
  script: ./scripts/deploy.sh
  skip_cleanup: true
  on:
    branch: master
