version: '2'

services:
  o2n_lumen:
    restart: always
    container_name: o2n_lumen
    build: images/lumen
    working_dir: /var/www/html/lumen
    volumes:
      - ./api/lumen:/var/www/html/lumen
    environment:
      - "WOOCOMMERCE_CONSUMER_KEY=ck_97f315f037d4d88e3214dd90c0982304adfabeae"
      - "WOOCOMMERCE_CONSUMER_SECRET=cs_da3df60a56e260266f0fb43ff5843573a2f4a03e"
      - "PAYPAL_CLIENT_ID=AY4uJnG0aQ8UQ_7CGFg6RqWlJqQGEHDFp8MCsmh0WCao_hqZPC5nMGAXlXiMj9-eKIBR8wpLEL1JlhUu"
      - "PAYPAL_CLIENT_SECRET=ENzIaOv5S1L7yE41m2vWOiowiVgoaOuqEEkDBtoNJIyYewxJXShBzm4zDmiMqtercOLpInxJIg71djj3"

  o2n_wordpress:
    restart: always
    container_name: o2n_wordpress
    build: images/wordpress
    working_dir: /var/www/html/wordpress
    volumes:
      - ./api/wordpress:/var/www/html/wordpress
    environment:
      - "ENV=development"
      - "WORDPRESS_DB_NAME=wordpress"
      - "WORDPRESS_DB_USER=wordpress"
      - "WORDPRESS_DB_HOST=o2n_wordpress_db:3306"
      - "WORDPRESS_DB_PASSWORD=password"

  o2n_nginx:
    restart: always
    container_name: o2n_nginx
    build: images/nginx/development
    volumes_from:
      - o2n_lumen
      - o2n_wordpress
    volumes:
      - ./logs:/var/www/logs
      - ./config/certs:/var/www/letsencrypt
      - ./client/dist:/var/www/html/client
    ports:
      - 80:80
      - 443:443

  o2n_lumen_db:
    restart: always
    container_name: o2n_lumen_db
    image: mariadb:latest
    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=password"

  o2n_wordpress_db:
    restart: always
    container_name: o2n_wordpress_db
    image: mariadb:latest
    environment:
      - "MYSQL_DATABASE=wordpress"
      - "MYSQL_USER=wordpress"
      - "MYSQL_PASSWORD=password"
      - "MYSQL_ROOT_PASSWORD=password"

  o2n_client:
    restart: always
    container_name: o2n_client
    build: images/client
    working_dir: /var/www/html/client
    command: npm run dev
    volumes:
      - ./client:/var/www/html/client
    ports:
      - "8081:8080"
